spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/product
    username: app1
    password: app1
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  instance:
    prefer-ip-address: true
    client:
      serviceUrl:
        defaultZone: http://localhost:8761

security:
  secret: OBITO-IS-MADARA-123456789123456789123456789