spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/order_schema
    username: app1
    password: app1
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          format_sql: true

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      spring.json.add.type.headers: true
      retries: 3                       # retry on failure
      properties:
        spring.json.trusted.packages: "*"
    consumer:
      bootstrap-servers: localhost:9092
      group-id: order-group        # consumer group for your service
      auto-offset-reset: earliest      # start from earliest if no offset
      enable-auto-commit: false        # manual commit for safety
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"


server:
  port: 8091

eureka:
  instance:
    prefer-ip-address: true
    client:
      serviceUrl:
        defaultZone: http://localhost:8761

security:
  secret: OBITO-IS-MADARA-123456789123456789123456789

kafka-event:
  inventory-release-topic: INVENTORY-RELEASE
  inventory-deduct-topic: INVENTORY-DEDUCT
  payment-failed-topic: PAYMENT-FAILED
  payment-success-topic: PAYMENT-SUCCESS